name: fmt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  fmt:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt
    - name: show toolchain
      run: rustup show
    - name: fmt
      run: cargo fmt --all -- --check
