name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Run Rust tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-05-02
        target: wasm32-unknown-unknown
        override: true
    - name: Run tests
      run: cargo test --locked --verbose --all
    - name: Ensure benchmarking compiles
      run: cargo check --release --features=runtime-benchmarks

  lint:
    name: 'Run lints'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-05-02
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt, clippy
    - name: Rustfmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all
