name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-11-06
        target: wasm32-unknown-unknown
        override: true
    - name: show toolchain
      run: rustup show
    - name: test
      run: cargo test --locked --verbose --all
